replicaCount: 1
image:
  repository: image-registry.openshift-image-registry.svc:5000/ecommerce/api-gateway
  tag: "latest"
  digest: ""
  pullPolicy: IfNotPresent

service:
  port: 8443

route:
  enabled: true
  host: "api-gateway-ecommerce.apps-crc.testing"
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  annotations: {}

env:
  SERVER_PORT: "8443"
  SERVER_SSL_ENABLED: "true"
  KEYCLOAK_ISSUER_URI: "https://keycloak-platform.apps-crc.testing/realms/master"
  GATEWAY_SSL_TRUSTSTORE: "/etc/ssl/openshift/truststore.jks"
  GATEWAY_SSL_TRUSTSTORE_PASSWORD: "changeit"
  GATEWAY_SSL_TRUSTSTORE_TYPE: "JKS"
  REVIEW_SERVICE_URL: "https://review-service-ecommerce.apps-crc.testing"
  CATALOG_SERVICE_URL: "https://catalog-service-ecommerce.apps-crc.testing"
  WISHLIST_SERVICE_URL: "https://wishlist-service-ecommerce.apps-crc.testing"
  CUSTOMER_SERVICE_URL: "https://customer-service-ecommerce.apps-crc.testing"
  CART_SERVICE_URL: "https://cart-service-ecommerce.apps-crc.testing"
  RETURNS_SERVICE_URL: "https://returns-service-ecommerce.apps-crc.testing"
  ORDER_SERVICE_URL: "https://order-service-ecommerce.apps-crc.testing"
  INVENTORY_SERVICE_URL: "https://inventory-service-ecommerce.apps-crc.testing"
  COUPON_SERVICE_URL: "https://coupon-service-ecommerce.apps-crc.testing"
  PRICING_SERVICE_URL: "https://pricing-service-ecommerce.apps-crc.testing"
  PAYMENT_SERVICE_URL: "https://payment-service-ecommerce.apps-crc.testing"
  SHIPPING_SERVICE_URL: "https://shipping-service-ecommerce.apps-crc.testing"
  NOTIFICATION_SERVICE_URL: "https://notification-service-ecommerce.apps-crc.testing"

secret:
  name: "api-gateway-secret"
  create: false
  data: {}
  # data example:
  #   DB_HOST: "db"
  #   DB_PORT: "5432"
  #   DB_NAME: "api-gateway"
  #   DB_USER: "api-gateway"
  #   DB_PASSWORD: "change-me"

secretEnv:
  {}

tls:
  enabled: true
  secretName: "wildcard-apps-tls"

truststore:
  enabled: true
  secretName: "platform-truststore"
  mountPath: "/etc/ssl/openshift"
  password: "changeit"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 20
  periodSeconds: 20

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
