replicaCount: 1
image:
  repository: image-registry.openshift-image-registry.svc:5000/ecommerce/api-gateway
  tag: "latest"
  digest: ""
  pullPolicy: IfNotPresent

service:
  port: 8443

route:
  enabled: true
  host: "api-gateway-ecommerce.apps.example.invalid"
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  annotations: {}

env:
  SERVER_PORT: "8443"
  SERVER_SSL_ENABLED: "true"
  KEYCLOAK_ISSUER_URI: "https://keycloak-platform.apps.example.invalid/realms/master"
  GATEWAY_SSL_TRUSTSTORE: "/etc/ssl/openshift/truststore.jks"
  GATEWAY_SSL_TRUSTSTORE_PASSWORD: "changeit"
  GATEWAY_SSL_TRUSTSTORE_TYPE: "JKS"
  REVIEW_SERVICE_URL: "http://review-service.ecommerce.svc.cluster.local:8443"
  CATALOG_SERVICE_URL: "http://catalog-service.ecommerce.svc.cluster.local:8443"
  WISHLIST_SERVICE_URL: "http://wishlist-service.ecommerce.svc.cluster.local:8443"
  CUSTOMER_SERVICE_URL: "http://customer-service.ecommerce.svc.cluster.local:8443"
  CART_SERVICE_URL: "http://cart-service.ecommerce.svc.cluster.local:8443"
  RETURNS_SERVICE_URL: "http://returns-service.ecommerce.svc.cluster.local:8443"
  ORDER_SERVICE_URL: "http://order-service.ecommerce.svc.cluster.local:8443"
  INVENTORY_SERVICE_URL: "http://inventory-service.ecommerce.svc.cluster.local:8443"
  COUPON_SERVICE_URL: "http://coupon-service.ecommerce.svc.cluster.local:8443"
  PRICING_SERVICE_URL: "http://pricing-service.ecommerce.svc.cluster.local:8443"
  PAYMENT_SERVICE_URL: "http://payment-service.ecommerce.svc.cluster.local:8443"
  SHIPPING_SERVICE_URL: "http://shipping-service.ecommerce.svc.cluster.local:8443"
  NOTIFICATION_SERVICE_URL: "http://notification-service.ecommerce.svc.cluster.local:8443"

secret:
  name: "api-gateway-secret"
  create: false
  data: {}
  # data example:
  #   DB_HOST: "db"
  #   DB_PORT: "5432"
  #   DB_NAME: "api-gateway"
  #   DB_USER: "api-gateway"
  #   DB_PASSWORD: "change-me"

secretEnv:
  {}

tls:
  enabled: true
  secretName: "wildcard-apps-tls"

truststore:
  enabled: true
  secretName: "platform-truststore"
  mountPath: "/etc/ssl/openshift"
  password: "changeit"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  path: /actuator/health
  initialDelaySeconds: 20
  periodSeconds: 20

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
